k = [('i_datum', '27.07.2020'),
     ('i_datum', '28.07.2020'),
     ('i_datum', '29.07.2020'),
     ('i_datum', '30.07.2020'),
     ('i_datum', '31.07.2020'),
     ('i_az', '01:00'), ('i_az', ''), ('i_az', ''), ('i_az', ''), ('i_az', ''),
     ('i_az', '01:00'), ('i_az', ''), ('i_az', ''), ('i_az', ''), ('i_az', ''),
     ('i_az', '01:00'), ('i_az', ''), ('i_az', ''), ('i_az', ''), ('i_az', ''),
     ('i_az', '01:00'), ('i_az', ''), ('i_az', ''), ('i_az', ''), ('i_az', ''),
     ('i_az', '01:00'), ('i_az', ''), ('i_az', ''), ('i_az', ''), ('i_az', ''),
     ('i_az', '01:00'), ('i_az', ''), ('i_az', ''), ('i_az', ''), ('i_az', ''),
     ('i_kg_id', ''), ('i_kg_id', ''), ('i_kg_id', ''), ('i_kg_id', ''), ('i_kg_id', ''),
     ('i_von', '27.07.2020'),
     ('i_sel', ''),
     ('i_bis', '31.07.2020'),
     ('i_ts_lock_az_arr', '0'), ('i_ts_lock_az_arr', '0'), ('i_ts_lock_az_arr', '0'),
     ('i_ts_lock_az_arr', '0'), ('i_ts_lock_az_arr', '0'), ('i_ts_lock_az_arr', '0'), ('i_ts_lock_az_arr', '0'),
     ('i_ts_lock_az_arr', '0'), ('i_ts_lock_az_arr', '0'), ('i_ts_lock_az_arr', '0'), ('i_ts_lock_az_arr', '0'),
     ('i_ts_lock_az_arr', '0'), ('i_ts_lock_az_arr', '0'), ('i_ts_lock_az_arr', '0'), ('i_ts_lock_az_arr', '0'),
     ('i_ts_lock_az_arr', '0'), ('i_ts_lock_az_arr', '0'), ('i_ts_lock_az_arr', '0'), ('i_ts_lock_az_arr', '0'),
     ('i_ts_lock_az_arr', '0'), ('i_ts_lock_az_arr', '0'), ('i_ts_lock_az_arr', '0'), ('i_ts_lock_az_arr', '0'),
     ('i_ts_lock_az_arr', '0'), ('i_ts_lock_az_arr', '0'), ('i_ts_lock_az_arr', '0'), ('i_ts_lock_az_arr', '0'),
     ('i_ts_lock_az_arr', '0'), ('i_ts_lock_az_arr', '0'), ('i_ts_lock_az_arr', '0'),
     ('i_user_tasks', '6'),
     ('i_action', 'Speichern'),
     ('i_kommentar', ''), ('i_kommentar', ''), ('i_kommentar', ''), ('i_kommentar', ''),
     ('i_kommentar', ''), ('i_kommentar', ''), ('i_kommentar', ''), ('i_kommentar', ''), ('i_kommentar', ''),
     ('i_kommentar', ''), ('i_kommentar', ''), ('i_kommentar', ''), ('i_kommentar', ''), ('i_kommentar', ''),
     ('i_kommentar', ''), ('i_kommentar', ''), ('i_kommentar', ''), ('i_kommentar', ''), ('i_kommentar', ''),
     ('i_kommentar', ''), ('i_kommentar', ''), ('i_kommentar', ''), ('i_kommentar', ''), ('i_kommentar', ''),
     ('i_kommentar', ''), ('i_kommentar', ''), ('i_kommentar', ''), ('i_kommentar', ''), ('i_kommentar', ''),
     ('i_kommentar', ''),
     ('i_ts_rt_la_id', ''), ('i_ts_rt_la_id', '1997994#2665878#LA_103960#'),
     ('i_ts_rt_la_id', '1997994#2665878#LA_103960#'), ('i_ts_rt_la_id', '1997994#2665878#LA_103960#'),
     ('i_ts_rt_la_id', '1997994#2665878#LA_103960#'), ('i_ts_rt_la_id', '1997994#2665878#LA_103960#'),
     ('i_geht', '13:33'), ('i_geht', '20:00'), ('i_geht', '20:00'), ('i_geht', '20:00'), ('i_geht', '20:00'),
     ('i_ts_lock_arr', '0'), ('i_ts_lock_arr', '0'), ('i_ts_lock_arr', '0'), ('i_ts_lock_arr', '0'),
     ('i_ts_lock_arr', '0'), ('i_ts_lock_arr', '0'),
     ('i_redirectmodus', ''),
     ('i_kommt', '06:00'), ('i_kommt', '06:00'), ('i_kommt', '06:00'), ('i_kommt', '06:00'), ('i_kommt', '06:00'),
     ('i_redirectto', '')]
